# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint, constr


class CleanupPolicy(Enum):
    revoke = 'revoke'
    remove_materialization = 'remove-materialization'
    retain_source = 'retain-source'


class Delivery(Enum):
    mount = 'mount'
    local_bridge = 'local-bridge'
    materialize = 'materialize'
    client = 'client'
    environment = 'environment'


class Mode(Enum):
    ro = 'ro'
    rw = 'rw'


class AttachmentCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cleanup_policy: CleanupPolicy | None = Field('revoke', title='Cleanup Policy')
    delivery: Delivery | None = Field('mount', title='Delivery')
    mode: Mode | None = Field('ro', title='Mode')
    mount_path: str | None = Field(None, title='Mount Path')
    required: bool | None = Field(True, title='Required')
    revision_uid: str | None = Field(None, title='Revision Uid')
    sandbox_provider: str = Field(..., title='Sandbox Provider')
    sandbox_uid: str = Field(..., title='Sandbox Uid')
    source_uid: str = Field(..., title='Source Uid')


class AttachmentLimits(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bytes: conint(ge=0) | None = Field(None, title='Bytes')
    queries: conint(ge=0) | None = Field(None, title='Queries')
    rows: conint(ge=0) | None = Field(None, title='Rows')


class AttachmentPrepare(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expires_at: str | None = Field(None, title='Expires At')
    token_audience: str | None = Field(None, title='Token Audience')


class AttachmentStatus(Enum):
    requested = 'requested'
    preparing = 'preparing'
    ready = 'ready'
    degraded = 'degraded'
    revoking = 'revoking'
    revoked = 'revoked'
    failed = 'failed'


class Status(Enum):
    ready = 'ready'
    degraded = 'degraded'
    failed = 'failed'
    revoked = 'revoked'


class CallerResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    roles: list[str] | None = Field(None, title='Roles')
    uid: str | int | None = Field(None, title='Uid')


class Capability(Enum):
    browse = 'browse'
    transfer = 'transfer'
    mount = 'mount'
    query = 'query'
    materialize = 'materialize'
    sync = 'sync'
    local_bridge_mount = 'local-bridge-mount'


class CloudObjectView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    etag: str | None = Field(None, title='Etag')
    is_directory: bool = Field(..., title='Is Directory')
    modified_at: str | None = Field(None, title='Modified At')
    path: str = Field(..., title='Path')
    size: int = Field(..., title='Size')


class AccessPreference(Enum):
    automatic = 'automatic'
    mount = 'mount'
    python = 'python'
    object_client = 'object-client'


class Origin(Enum):
    datalayer_shared = 'datalayer-shared'
    environment = 'environment'
    user = 'user'


class Provider(Enum):
    s3 = 's3'
    gcs = 'gcs'
    r2 = 'r2'
    azure_blob = 'azure-blob'
    s3_compatible = 's3-compatible'
    datalayer_shared_fs = 'datalayer-shared-fs'


class CloudStorageConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    access_preference: AccessPreference | None = Field(
        'automatic', title='Access Preference'
    )
    bucket_or_container: str = Field(..., title='Bucket Or Container')
    cache_policy: str | None = Field(None, title='Cache Policy')
    credential_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Credential Uid')
    )
    endpoint: str | None = Field(None, title='Endpoint')
    expected_consistency: str | None = Field(None, title='Expected Consistency')
    kind: Literal['cloud-storage'] = Field(..., title='Kind')
    mount_implementation: str | None = Field(None, title='Mount Implementation')
    origin: Origin | None = Field('user', title='Origin')
    prefix: str | None = Field('', title='Prefix')
    provider: Provider = Field(..., title='Provider')
    python_implementation: str | None = Field(None, title='Python Implementation')
    region: str | None = Field(None, title='Region')


class Use(Enum):
    local = 'local'
    remote = 'remote'
    keep_both = 'keep-both'


class ConflictResolution(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    use: Use = Field(..., title='Use')


class ConnectionTest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    detail: str = Field(..., title='Detail')
    ok: bool = Field(..., title='Ok')
    provider: str = Field(..., title='Provider')


class AccessMode(Enum):
    mount = 'mount'
    python = 'python'
    object_client = 'object-client'


class FilesystemPrimitive(Enum):
    list = 'list'
    stat = 'stat'
    read = 'read'
    write = 'write'
    mkdir = 'mkdir'
    remove = 'remove'
    upload = 'upload'
    download = 'download'


class Kind(Enum):
    file = 'file'
    folder = 'folder'


class ContentObject(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    checksum: str | None = Field(None, title='Checksum')
    checksum_algorithm: str | None = Field(None, title='Checksum Algorithm')
    created_at: str = Field(..., title='Created At')
    created_by_uid: str = Field(..., title='Created By Uid')
    current_version_uid: str | None = Field(None, title='Current Version Uid')
    deleted: bool = Field(..., title='Deleted')
    kind: Kind = Field(..., title='Kind')
    media_type: str = Field(..., title='Media Type')
    path: str = Field(..., title='Path')
    size: int = Field(..., title='Size')
    source_uid: str = Field(..., title='Source Uid')
    uid: str = Field(..., title='Uid')
    updated_at: str = Field(..., title='Updated At')


class ContentObjectVersion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    checksum: str | None = Field(None, title='Checksum')
    checksum_algorithm: str | None = Field(None, title='Checksum Algorithm')
    created_at: str = Field(..., title='Created At')
    created_by_uid: str = Field(..., title='Created By Uid')
    deleted: bool = Field(..., title='Deleted')
    media_type: str = Field(..., title='Media Type')
    object_uid: str = Field(..., title='Object Uid')
    path: str = Field(..., title='Path')
    provenance: dict[str, Any] = Field(..., title='Provenance')
    size: int = Field(..., title='Size')
    source_uid: str = Field(..., title='Source Uid')
    uid: str = Field(..., title='Uid')


class Kind1(Enum):
    files = 'files'
    dataset = 'dataset'
    volume = 'volume'
    cloud_storage = 'cloud-storage'
    datasource = 'datasource'
    data_server = 'data-server'
    mcp = 'mcp'
    environment = 'environment'


class CredentialDiagnostics(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    credential_name: str | None = Field(None, title='Credential Name')
    credential_uid: str | None = Field(..., title='Credential Uid')
    detail: str = Field(..., title='Detail')
    referenced: bool = Field(..., title='Referenced')
    resolvable: bool = Field(..., title='Resolvable')
    source_uid: str = Field(..., title='Source Uid')


class CredentialRotation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    credential_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Credential Uid'
    )


class DataServerConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    connectors: list[str] | None = Field(None, title='Connectors')
    kind: Literal['data-server'] = Field(..., title='Kind')
    last_heartbeat_at: AwareDatetime | None = Field(None, title='Last Heartbeat At')
    mtls_issuer: str = Field(..., title='Mtls Issuer')
    policy_version: str = Field(..., title='Policy Version')
    registration_identity: str = Field(..., title='Registration Identity')


class DatasetConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    current_revision_uid: (
        constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None
    ) = Field(None, title='Current Revision Uid')
    kind: Literal['dataset'] = Field(..., title='Kind')
    license: str | None = Field(None, title='License')
    publication_eligible: bool | None = Field(False, title='Publication Eligible')
    schema_notes: str | None = Field(None, title='Schema Notes')
    tags: list[str] | None = Field(None, title='Tags')


class DatasetPublication(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actor_uid: str = Field(..., title='Actor Uid')
    created_at: str = Field(..., title='Created At')
    description: str | None = Field(None, title='Description')
    file_count: int = Field(..., title='File Count')
    license: str | None = Field(None, title='License')
    manifest_checksum: str = Field(..., title='Manifest Checksum')
    name: str = Field(..., title='Name')
    owner_uid: str = Field(..., title='Owner Uid')
    revision_uid: str = Field(..., title='Revision Uid')
    source_uid: str = Field(..., title='Source Uid')
    status: str = Field(..., title='Status')
    tags: list[str] | None = Field(None, title='Tags')
    total_size: int = Field(..., title='Total Size')
    uid: str = Field(..., title='Uid')
    unpublished_at: str | None = Field(None, title='Unpublished At')
    unpublished_by: str | None = Field(None, title='Unpublished By')


class DatasetPublicationCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    revision_uid: str = Field(..., title='Revision Uid')


class DatasetPublicationList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[DatasetPublication] = Field(..., title='Items')


class OriginKind(Enum):
    upload = 'upload'
    home_folder = 'home-folder'
    sandbox_result = 'sandbox-result'
    cloud_storage = 'cloud-storage'
    volume = 'volume'


class DatasetRevisionFile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    checksum: str = Field(..., title='Checksum')
    media_type: str = Field(..., title='Media Type')
    object_uid: str = Field(..., title='Object Uid')
    path: str = Field(..., title='Path')
    size: int = Field(..., title='Size')
    uid: str = Field(..., title='Uid')
    version_uid: str = Field(..., title='Version Uid')


class DatasetRevisionFileCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    object_uid: str | None = Field(None, title='Object Uid')
    path: str | None = Field(None, title='Path')
    source_path: str | None = Field(None, title='Source Path')
    source_uid: str | None = Field(None, title='Source Uid')
    version_uid: str | None = Field(None, title='Version Uid')


class DatasourceConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allowed_operations: list[str] | None = Field(None, title='Allowed Operations')
    connector_type: str = Field(..., title='Connector Type')
    credential_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Credential Uid')
    )
    data_server_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Data Server Uid')
    )
    database_or_project: str | None = Field(None, title='Database Or Project')
    default_row_limit: conint(ge=1) | None = Field(None, title='Default Row Limit')
    endpoint: str | None = Field(None, title='Endpoint')
    kind: Literal['datasource'] = Field(..., title='Kind')
    network_route: str | None = Field(None, title='Network Route')


class DependencyStatusResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configured: bool = Field(..., title='Configured')
    detail: str = Field(..., title='Detail')
    name: str = Field(..., title='Name')
    ready: bool = Field(..., title='Ready')
    required: bool = Field(..., title='Required')


class EffectiveAccessLevel(Enum):
    view = 'view'
    update = 'update'
    execute = 'execute'


class EffectivePermissions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    effective_access_level: EffectiveAccessLevel | None = Field(
        ..., title='Effective Access Level'
    )
    execute: bool = Field(..., title='Execute')
    is_owner: bool = Field(..., title='Is Owner')
    update: bool = Field(..., title='Update')
    view: bool = Field(..., title='View')


class EnvironmentBuildEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    destination_path: str = Field(..., title='Destination Path')
    sha256: constr(pattern=r'^[0-9a-f]{64}$') = Field(..., title='Sha256')
    size_bytes: conint(ge=0) = Field(..., title='Size Bytes')
    source_uri: str = Field(..., title='Source Uri')


class EnvironmentConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    build_entries: list[EnvironmentBuildEntry] | None = Field(
        None, title='Build Entries'
    )
    build_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Build Uid'
    )
    environment_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Environment Uid'
    )
    kind: Literal['environment'] = Field(..., title='Kind')
    resolved_provider_paths: dict[str, str] | None = Field(
        None, title='Resolved Provider Paths'
    )
    runtime_content_uids: (
        list[constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$')] | None
    ) = Field(None, title='Runtime Content Uids')


class FilesConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['files'] = Field(..., title='Kind')
    owning_user_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Owning User Uid'
    )
    quota_policy: str = Field(..., title='Quota Policy')
    storage_backend_id: str = Field(..., title='Storage Backend Id')
    versioning_policy: str = Field(..., title='Versioning Policy')


class AccessLevel(Enum):
    view = 'view'
    update = 'update'
    execute = 'execute'


class PrincipalKind(Enum):
    user = 'user'
    team = 'team'
    organization = 'organization'


class Grant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    access_level: AccessLevel = Field(..., title='Access Level')
    principal_kind: PrincipalKind = Field(..., title='Principal Kind')
    principal_uid: str = Field(..., title='Principal Uid')
    uid: str | None = Field(None, title='Uid')


class HealthResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    service: Literal['contents'] = Field('contents', title='Service')
    status: Literal['healthy'] = Field('healthy', title='Status')
    success: Literal[True] = Field(True, title='Success')


class HomeFolderFileEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    is_directory: bool = Field(..., title='Is Directory')
    modified_at: str | None = Field(None, title='Modified At')
    name: str = Field(..., title='Name')
    path: str = Field(..., title='Path')
    scope: str | None = Field(None, title='Scope')
    size: int = Field(..., title='Size')
    title: str | None = Field(None, title='Title')


class HomeFolderFileList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[HomeFolderFileEntry] = Field(..., title='Items')
    path: str = Field(..., title='Path')


class HomeFolderQuota(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    limit_bytes: int = Field(..., title='Limit Bytes')
    limit_objects: int = Field(..., title='Limit Objects')
    reserved_bytes: int = Field(..., title='Reserved Bytes')
    reserved_objects: int = Field(..., title='Reserved Objects')
    used_bytes: int = Field(..., title='Used Bytes')
    used_objects: int = Field(..., title='Used Objects')


class ManifestEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    blocks: list[str] | None = Field(None, title='Blocks')
    checksum: constr(pattern=r'^[0-9a-f]{64}$') = Field(..., title='Checksum')
    modified_at: str = Field(..., title='Modified At')
    path: str = Field(..., title='Path')
    size: conint(ge=0) = Field(..., title='Size')


class ManifestPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    block_size: int | None = Field(4194304, title='Block Size')
    entries: list[ManifestEntry] | None = Field(None, title='Entries')
    tombstones: dict[str, str] | None = Field(None, title='Tombstones')


class Transport(Enum):
    stdio = 'stdio'
    streamable_http = 'streamable-http'
    sse = 'sse'


class McpConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allowed_domains: list[str] | None = Field(None, title='Allowed Domains')
    allowed_resources: list[str] | None = Field(None, title='Allowed Resources')
    allowed_tools: list[str] | None = Field(None, title='Allowed Tools')
    approval_policy: str = Field(..., title='Approval Policy')
    credential_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Credential Uid')
    )
    destination_policy: str = Field(..., title='Destination Policy')
    endpoint: str | None = Field(None, title='Endpoint')
    kind: Literal['mcp'] = Field(..., title='Kind')
    managed_server_uid: (
        constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None
    ) = Field(None, title='Managed Server Uid')
    transport: Transport = Field(..., title='Transport')


class ObjectList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[ContentObject] = Field(..., title='Items')
    next_cursor: str | None = Field(None, title='Next Cursor')


class OperationCapability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    available: bool = Field(..., title='Available')
    deployed: bool = Field(..., title='Deployed')
    documentation: str | None = Field(None, title='Documentation')
    kind: Literal['operation'] = Field('operation', title='Kind')
    label: str = Field(..., title='Label')
    name: str = Field(..., title='Name')
    reason: str | None = Field(None, title='Reason')


class Status1(Enum):
    pending = 'pending'
    running = 'running'
    succeeded = 'succeeded'
    failed = 'failed'
    cancelling = 'cancelling'
    cancelled = 'cancelled'


class OperationView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: int = Field(..., title='Attempt')
    cancellation_requested: bool = Field(..., title='Cancellation Requested')
    completed_at: str | None = Field(None, title='Completed At')
    created_at: str = Field(..., title='Created At')
    error_code: str | None = Field(None, title='Error Code')
    error_message: str | None = Field(None, title='Error Message')
    max_attempts: int = Field(..., title='Max Attempts')
    operation_kind: str = Field(..., title='Operation Kind')
    result: dict[str, Any] | None = Field(None, title='Result')
    source_uid: str | None = Field(None, title='Source Uid')
    status: Status1 = Field(..., title='Status')
    uid: str = Field(..., title='Uid')
    updated_at: str = Field(..., title='Updated At')


class PingResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: Literal['Pong.'] = Field('Pong.', title='Message')
    success: Literal[True] = Field(True, title='Success')
    version: str = Field(..., title='Version')


class Kind3(Enum):
    upload = 'upload'
    download = 'download'
    delete_remote = 'delete_remote'
    delete_local = 'delete_local'
    conflict = 'conflict'


class PlanAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    blocks: list[int] | None = Field(None, title='Blocks')
    kind: Kind3 = Field(..., title='Kind')
    object_uid: str | None = Field(None, title='Object Uid')
    path: str = Field(..., title='Path')
    reason: str = Field(..., title='Reason')
    version_uid: str | None = Field(None, title='Version Uid')


class Operation(Enum):
    get = 'get'
    put = 'put'


class PresignedAccess(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expires_in: int = Field(..., title='Expires In')
    operation: Operation = Field(..., title='Operation')
    path: str = Field(..., title='Path')
    url: str = Field(..., title='Url')


class QuarantineRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reason: str = Field(..., title='Reason')


class Status2(Enum):
    ready = 'ready'
    not_ready = 'not-ready'


class ReadinessResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dependencies: list[DependencyStatusResponse] = Field(..., title='Dependencies')
    service: Literal['contents'] = Field('contents', title='Service')
    status: Status2 = Field(..., title='Status')
    success: bool = Field(..., title='Success')


class RestoreRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version_uid: str = Field(..., title='Version Uid')


class ServiceStatusResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    caller: CallerResponse
    service: Literal['contents'] = Field('contents', title='Service')
    success: Literal[True] = Field(True, title='Success')
    version: str = Field(..., title='Version')


class Sharing(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    grants: list[Grant] | None = Field(None, title='Grants')


class SourceKindCapability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    available: bool = Field(..., title='Available')
    count: int = Field(..., title='Count')
    creatable: bool = Field(..., title='Creatable')
    deployed: bool = Field(..., title='Deployed')
    documentation: str | None = Field(None, title='Documentation')
    kind: str = Field(..., title='Kind')
    label: str = Field(..., title='Label')
    name: str = Field(..., title='Name')
    reason: str | None = Field(None, title='Reason')


class SourceStatus(Enum):
    pending = 'pending'
    ready = 'ready'
    degraded = 'degraded'
    disabled = 'disabled'
    failed = 'failed'


class StableErrorCode(Enum):
    UNAUTHENTICATED = 'UNAUTHENTICATED'
    FORBIDDEN = 'FORBIDDEN'
    NOT_FOUND = 'NOT_FOUND'
    CONFLICT = 'CONFLICT'
    QUOTA_EXCEEDED = 'QUOTA_EXCEEDED'
    CAPABILITY_UNAVAILABLE = 'CAPABILITY_UNAVAILABLE'
    CHECKSUM_MISMATCH = 'CHECKSUM_MISMATCH'
    PROVIDER_UNAVAILABLE = 'PROVIDER_UNAVAILABLE'
    CAPABILITY_REVOKED = 'CAPABILITY_REVOKED'
    OPERATION_CANCELLED = 'OPERATION_CANCELLED'
    INTERNAL_ERROR = 'INTERNAL_ERROR'


class Resolution(Enum):
    local = 'local'
    remote = 'remote'
    keep_both = 'keep-both'


class Status3(Enum):
    open = 'open'
    resolved = 'resolved'


class SyncConflictView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    created_at: str = Field(..., title='Created At')
    local_entry: ManifestEntry | None = None
    path: str = Field(..., title='Path')
    reason: str = Field(..., title='Reason')
    remote_entry: ManifestEntry | None = None
    resolution: Resolution | None = Field(None, title='Resolution')
    resolved_at: str | None = Field(None, title='Resolved At')
    session_uid: str = Field(..., title='Session Uid')
    status: Status3 = Field(..., title='Status')
    uid: str = Field(..., title='Uid')


class ConflictPolicy(Enum):
    manual = 'manual'
    newest = 'newest'
    local = 'local'
    remote = 'remote'


class Direction(Enum):
    push = 'push'
    pull = 'pull'
    bidirectional = 'bidirectional'


class SyncCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    block_size: int | None = Field(4194304, title='Block Size')
    conflict_policy: ConflictPolicy | None = Field('manual', title='Conflict Policy')
    delete: bool | None = Field(False, title='Delete')
    direction: Direction | None = Field('bidirectional', title='Direction')
    exclusions: list[str] | None = Field(None, title='Exclusions')
    local_manifest: ManifestPayload
    remote_uri: str = Field(..., title='Remote Uri')
    watch: bool | None = Field(False, title='Watch')


class SyncPlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actions: list[PlanAction] | None = Field(None, title='Actions')


class SyncReconcile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    local_manifest: ManifestPayload


class SyncReport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    applied: list[str] | None = Field(None, title='Applied')
    failed: dict[str, str] | None = Field(None, title='Failed')
    transferred_bytes: conint(ge=0) | None = Field(0, title='Transferred Bytes')


class SyncSessionView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    block_size: int = Field(..., title='Block Size')
    completed_at: str | None = Field(None, title='Completed At')
    conflict_count: int = Field(..., title='Conflict Count')
    conflict_policy: str = Field(..., title='Conflict Policy')
    created_at: str = Field(..., title='Created At')
    delete: bool = Field(..., title='Delete')
    deleted_files: int = Field(..., title='Deleted Files')
    direction: str = Field(..., title='Direction')
    downloaded_files: int = Field(..., title='Downloaded Files')
    error_code: str | None = Field(None, title='Error Code')
    error_message: str | None = Field(None, title='Error Message')
    exclusions: list[str] = Field(..., title='Exclusions')
    last_heartbeat_at: str | None = Field(None, title='Last Heartbeat At')
    plan: SyncPlan | None = None
    reconciliations: int = Field(..., title='Reconciliations')
    remote_uri: str = Field(..., title='Remote Uri')
    source_uid: str = Field(..., title='Source Uid')
    status: str = Field(..., title='Status')
    transferred_bytes: int = Field(..., title='Transferred Bytes')
    uid: str = Field(..., title='Uid')
    updated_at: str = Field(..., title='Updated At')
    uploaded_files: int = Field(..., title='Uploaded Files')
    watch: bool = Field(..., title='Watch')


class Overwrite(Enum):
    reject = 'reject'
    replace_ = 'replace'
    new_version = 'new-version'


class TransferCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    checksum: constr(pattern=r'^[0-9a-f]{64}$') = Field(..., title='Checksum')
    destination_uri: str = Field(..., title='Destination Uri')
    direction: Literal['upload'] = Field('upload', title='Direction')
    media_type: str | None = Field('application/octet-stream', title='Media Type')
    overwrite: Overwrite | None = Field('reject', title='Overwrite')
    size: conint(ge=0) = Field(..., title='Size')


class TransferPart(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    checksum: str = Field(..., title='Checksum')
    number: int = Field(..., title='Number')
    size: int = Field(..., title='Size')


class TransferView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    completed_at: str | None = Field(None, title='Completed At')
    created_at: str = Field(..., title='Created At')
    destination_uri: str | None = Field(None, title='Destination Uri')
    direction: str = Field(..., title='Direction')
    error_code: str | None = Field(None, title='Error Code')
    error_message: str | None = Field(None, title='Error Message')
    expected_checksum: str = Field(..., title='Expected Checksum')
    expected_size: int = Field(..., title='Expected Size')
    media_type: str = Field(..., title='Media Type')
    object_uid: str | None = Field(None, title='Object Uid')
    overwrite_policy: str = Field(..., title='Overwrite Policy')
    part_count: int = Field(..., title='Part Count')
    parts: list[TransferPart] | None = Field(None, title='Parts')
    path: str = Field(..., title='Path')
    received_bytes: int = Field(..., title='Received Bytes')
    source_uid: str = Field(..., title='Source Uid')
    source_uri: str | None = Field(None, title='Source Uri')
    status: str = Field(..., title='Status')
    uid: str = Field(..., title='Uid')
    updated_at: str = Field(..., title='Updated At')
    version_uid: str | None = Field(None, title='Version Uid')


class ValidationError(BaseModel):
    ctx: dict[str, Any] | None = Field(None, title='Context')
    input: Any | None = Field(None, title='Input')
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class VersionList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[ContentObjectVersion] = Field(..., title='Items')
    next_cursor: str | None = Field(None, title='Next Cursor')


class AccessMode1(Enum):
    ro = 'ro'
    rw = 'rw'


class Scope(Enum):
    user = 'user'
    space = 'space'


class VolumeConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    access_modes: list[AccessMode1] = Field(..., title='Access Modes')
    backing_resource_id: str | None = Field(None, title='Backing Resource Id')
    capacity_bytes: conint(ge=1) = Field(..., title='Capacity Bytes')
    concurrent_readers: bool = Field(..., title='Concurrent Readers')
    concurrent_writers: bool = Field(..., title='Concurrent Writers')
    default_mount_path: str = Field(..., title='Default Mount Path')
    kind: Literal['volume'] = Field(..., title='Kind')
    scope: Scope = Field(..., title='Scope')
    storage_class: str | None = Field(None, title='Storage Class')


class AttachmentError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: StableErrorCode
    message: str = Field(..., title='Message')
    retryable: bool = Field(..., title='Retryable')


class AttachmentStatusUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capabilities: list[Capability] | None = Field(None, title='Capabilities')
    error: AttachmentError | None = None
    provider_resource_id: str | None = Field(None, title='Provider Resource Id')
    status: Status = Field(..., title='Status')


class CloudObjectList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[CloudObjectView] = Field(..., title='Items')
    next_cursor: str | None = Field(None, title='Next Cursor')


class ContentAttachment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    access_mode: AccessMode | None = Field(None, title='Access Mode')
    capabilities: list[Capability] | None = Field(None, title='Capabilities')
    cleanup_policy: CleanupPolicy | None = Field('revoke', title='Cleanup Policy')
    created_at: AwareDatetime = Field(..., title='Created At')
    delivery: Delivery = Field(..., title='Delivery')
    error: AttachmentError | None = None
    expires_at: AwareDatetime | None = Field(None, title='Expires At')
    fallback_reason: str | None = Field(None, title='Fallback Reason')
    filesystem_primitives: list[FilesystemPrimitive] | None = Field(
        None, title='Filesystem Primitives'
    )
    last_seen_at: AwareDatetime | None = Field(None, title='Last Seen At')
    limits: AttachmentLimits | None = None
    mode: Mode = Field(..., title='Mode')
    mount_path: str | None = Field(None, title='Mount Path')
    provider_resource_id: str | None = Field(None, title='Provider Resource Id')
    ready_at: AwareDatetime | None = Field(None, title='Ready At')
    required: bool | None = Field(True, title='Required')
    revision_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Revision Uid')
    )
    revoked_at: AwareDatetime | None = Field(None, title='Revoked At')
    sandbox_provider: str = Field(..., title='Sandbox Provider')
    sandbox_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Sandbox Uid'
    )
    source_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Source Uid'
    )
    status: AttachmentStatus
    token_audience: str | None = Field(None, title='Token Audience')
    uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Uid'
    )


class ContentAttachmentManifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attachments: list[ContentAttachment] = Field(..., title='Attachments')
    contract_version: Literal['v1'] = Field(..., title='Contract Version')
    generated_at: AwareDatetime = Field(..., title='Generated At')
    sandbox_provider: str = Field(..., title='Sandbox Provider')
    sandbox_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Sandbox Uid'
    )


class ContentSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capabilities: list[Capability] | None = Field(None, title='Capabilities')
    configuration: (
        FilesConfiguration
        | DatasetConfiguration
        | VolumeConfiguration
        | CloudStorageConfiguration
        | DatasourceConfiguration
        | DataServerConfiguration
        | McpConfiguration
        | EnvironmentConfiguration
    ) = Field(..., discriminator='kind', title='Configuration')
    contract_version: Literal['v1'] = Field(..., title='Contract Version')
    created_at: AwareDatetime = Field(..., title='Created At')
    credential_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Credential Uid')
    )
    description: str | None = Field(None, title='Description')
    kind: Kind1 = Field(..., title='Kind')
    name: constr(min_length=1) = Field(..., title='Name')
    principal_kind: PrincipalKind
    principal_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Principal Uid'
    )
    space_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = Field(
        None, title='Space Uid'
    )
    status: SourceStatus
    uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Uid'
    )
    updated_at: AwareDatetime = Field(..., title='Updated At')


class ContentSourceCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capabilities: list[Capability] | None = Field(None, title='Capabilities')
    configuration: (
        FilesConfiguration
        | DatasetConfiguration
        | VolumeConfiguration
        | CloudStorageConfiguration
        | DatasourceConfiguration
        | DataServerConfiguration
        | McpConfiguration
        | EnvironmentConfiguration
    ) = Field(..., discriminator='kind', title='Configuration')
    credential_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Credential Uid')
    )
    description: str | None = Field(None, title='Description')
    kind: Kind1 = Field(..., title='Kind')
    name: constr(min_length=1) = Field(..., title='Name')
    principal_kind: PrincipalKind | None = None
    principal_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Principal Uid')
    )
    space_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = Field(
        None, title='Space Uid'
    )


class ContentSourceUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capabilities: list[Capability] | None = Field(None, title='Capabilities')
    configuration: (
        FilesConfiguration
        | DatasetConfiguration
        | VolumeConfiguration
        | CloudStorageConfiguration
        | DatasourceConfiguration
        | DataServerConfiguration
        | McpConfiguration
        | EnvironmentConfiguration
        | None
    ) = Field(None, title='Configuration')
    credential_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Credential Uid')
    )
    description: str | None = Field(None, title='Description')
    name: constr(min_length=1) | None = Field(None, title='Name')
    status: SourceStatus | None = None


class ContentsCapabilities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    counts_truncated: bool = Field(..., title='Counts Truncated')
    operations: list[OperationCapability] = Field(..., title='Operations')
    source_kinds: list[SourceKindCapability] = Field(..., title='Source Kinds')


class DatasetRevision(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actor_uid: str = Field(..., title='Actor Uid')
    created_at: str = Field(..., title='Created At')
    file_count: int = Field(..., title='File Count')
    files: list[DatasetRevisionFile] | None = Field(None, title='Files')
    manifest_checksum: str = Field(..., title='Manifest Checksum')
    origin_kind: str = Field(..., title='Origin Kind')
    source_uid: str = Field(..., title='Source Uid')
    status: str = Field(..., title='Status')
    total_size: int = Field(..., title='Total Size')
    uid: str = Field(..., title='Uid')


class DatasetRevisionCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    files: list[DatasetRevisionFileCreate] = Field(..., min_length=1, title='Files')
    origin_kind: OriginKind = Field(..., title='Origin Kind')


class DatasetRevisionList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[DatasetRevision] = Field(..., title='Items')


class DeadLetterList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[OperationView] = Field(..., title='Items')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class SyncConflictList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[SyncConflictView] = Field(..., title='Items')


class SyncSessionList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[SyncSessionView] = Field(..., title='Items')
    next_cursor: str | None = Field(None, title='Next Cursor')


class TransferList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[TransferView] = Field(..., title='Items')
    next_cursor: str | None = Field(None, title='Next Cursor')


class AttachmentList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[ContentAttachment] = Field(..., title='Items')


class CatalogSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    permissions: EffectivePermissions
    source: ContentSource


class SourceList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[CatalogSource] = Field(..., title='Items')
    next_cursor: str | None = Field(None, title='Next Cursor')
