# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint, constr


class AttachmentCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cleanup_policy: (
        Literal['revoke', 'remove-materialization', 'retain-source'] | None
    ) = Field('revoke', title='Cleanup Policy')
    delivery: (
        Literal['mount', 'local-bridge', 'materialize', 'client', 'environment'] | None
    ) = Field('mount', title='Delivery')
    mode: Literal['ro', 'rw'] | None = Field('ro', title='Mode')
    mount_path: str | None = Field(None, title='Mount Path')
    required: bool | None = Field(True, title='Required')
    revision_uid: str | None = Field(None, title='Revision Uid')
    sandbox_provider: str = Field(..., title='Sandbox Provider')
    sandbox_uid: str = Field(..., title='Sandbox Uid')
    source_uid: str = Field(..., title='Source Uid')


class AttachmentLimits(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bytes: conint(ge=0) | None = Field(None, title='Bytes')
    queries: conint(ge=0) | None = Field(None, title='Queries')
    rows: conint(ge=0) | None = Field(None, title='Rows')


class AttachmentPrepare(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expires_at: str | None = Field(None, title='Expires At')
    token_audience: str | None = Field(None, title='Token Audience')


class BodyWritePartApiContentsV1PublishedTablesRelationPartsPartPut(BaseModel):
    file: str = Field(..., title='File')


class BridgeCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    exclusions: list[str] | None = Field(None, title='Exclusions')
    local_root_fingerprint: constr(pattern=r'^[0-9a-f]{64}$') = Field(
        ..., title='Local Root Fingerprint'
    )


class BridgeMountGrant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bridge_uid: str = Field(..., title='Bridge Uid')
    expires_at: str = Field(..., title='Expires At')
    mode: Literal['ro', 'rw'] = Field(..., title='Mode')
    mount_path: str = Field(..., title='Mount Path')
    mount_token: str = Field(..., title='Mount Token')
    relay_url: str = Field(..., title='Relay Url')
    session_key: str = Field(..., title='Session Key')


class BridgeSession(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attachment_uid: str = Field(..., title='Attachment Uid')
    client_seen_at: str | None = Field(None, title='Client Seen At')
    created_at: str = Field(..., title='Created At')
    exclusions: list[str] | None = Field(None, title='Exclusions')
    expires_at: str = Field(..., title='Expires At')
    local_root_fingerprint: str = Field(..., title='Local Root Fingerprint')
    mode: Literal['ro', 'rw'] = Field(..., title='Mode')
    mount_path: str = Field(..., title='Mount Path')
    mount_seen_at: str | None = Field(None, title='Mount Seen At')
    owner_uid: str = Field(..., title='Owner Uid')
    revoked_at: str | None = Field(None, title='Revoked At')
    sandbox_uid: str = Field(..., title='Sandbox Uid')
    state: Literal[
        'pending', 'connected', 'reconnecting', 'disconnected', 'revoked', 'expired'
    ] = Field(..., title='State')
    uid: str = Field(..., title='Uid')
    updated_at: str = Field(..., title='Updated At')


class BridgeStateReport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: Literal['client', 'mount'] = Field(..., title='Role')
    state: Literal['connected', 'reconnecting', 'disconnected'] = Field(
        ..., title='State'
    )


class CallerResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    roles: list[str] | None = Field(None, title='Roles')
    uid: str | int | None = Field(None, title='Uid')


class CapabilityTicket(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expires_at: str = Field(..., title='Expires At')
    flight_endpoint: str | None = Field(None, title='Flight Endpoint')
    https_fallback_url: str = Field(..., title='Https Fallback Url')
    ticket: str = Field(..., title='Ticket')


class CapabilityTicketMint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expires_in: conint(ge=1) | None = Field(None, title='Expires In')
    query_uid: str = Field(..., title='Query Uid')
    sandbox_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Sandbox Uid'
    )


class CapabilityTicketRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expires_in: conint(ge=1) | None = Field(None, title='Expires In')
    sandbox_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Sandbox Uid')
    )


class CertificateAuthorityView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ca_certificate: str = Field(..., title='Ca Certificate')
    ephemeral: bool = Field(..., title='Ephemeral')


class CertificateSigningRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    csr: constr(min_length=1) = Field(..., title='Csr')


class CloudObjectView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    etag: str | None = Field(None, title='Etag')
    is_directory: bool = Field(..., title='Is Directory')
    modified_at: str | None = Field(None, title='Modified At')
    path: str = Field(..., title='Path')
    size: int = Field(..., title='Size')


class CloudStorageConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    access_preference: (
        Literal['automatic', 'mount', 'python', 'object-client'] | None
    ) = Field('automatic', title='Access Preference')
    bucket_or_container: str = Field(..., title='Bucket Or Container')
    cache_policy: str | None = Field(None, title='Cache Policy')
    credential_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Credential Uid')
    )
    endpoint: str | None = Field(None, title='Endpoint')
    expected_consistency: str | None = Field(None, title='Expected Consistency')
    kind: Literal['cloud-storage'] = Field(..., title='Kind')
    mount_implementation: str | None = Field(None, title='Mount Implementation')
    mount_role_arn: str | None = Field(None, title='Mount Role Arn')
    mount_session_seconds: int | None = Field(3600, title='Mount Session Seconds')
    origin: Literal['datalayer-shared', 'environment', 'user'] | None = Field(
        'user', title='Origin'
    )
    prefix: str | None = Field('', title='Prefix')
    provider: Literal[
        's3', 'gcs', 'r2', 'azure-blob', 's3-compatible', 'datalayer-shared-fs'
    ] = Field(..., title='Provider')
    python_implementation: str | None = Field(None, title='Python Implementation')
    region: str | None = Field(None, title='Region')


class ConflictResolution(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    use: Literal['local', 'remote', 'keep-both'] = Field(..., title='Use')


class ConnectionTest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    detail: str = Field(..., title='Detail')
    ok: bool = Field(..., title='Ok')
    provider: str = Field(..., title='Provider')


class ContentObject(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    checksum: str | None = Field(None, title='Checksum')
    checksum_algorithm: str | None = Field(None, title='Checksum Algorithm')
    created_at: str = Field(..., title='Created At')
    created_by_uid: str = Field(..., title='Created By Uid')
    current_version_uid: str | None = Field(None, title='Current Version Uid')
    deleted: bool = Field(..., title='Deleted')
    kind: Literal['file', 'folder'] = Field(..., title='Kind')
    media_type: str = Field(..., title='Media Type')
    path: str = Field(..., title='Path')
    size: int = Field(..., title='Size')
    source_uid: str = Field(..., title='Source Uid')
    uid: str = Field(..., title='Uid')
    updated_at: str = Field(..., title='Updated At')


class ContentObjectVersion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    checksum: str | None = Field(None, title='Checksum')
    checksum_algorithm: str | None = Field(None, title='Checksum Algorithm')
    created_at: str = Field(..., title='Created At')
    created_by_uid: str = Field(..., title='Created By Uid')
    deleted: bool = Field(..., title='Deleted')
    media_type: str = Field(..., title='Media Type')
    object_uid: str = Field(..., title='Object Uid')
    path: str = Field(..., title='Path')
    provenance: dict[str, Any] = Field(..., title='Provenance')
    size: int = Field(..., title='Size')
    source_uid: str = Field(..., title='Source Uid')
    uid: str = Field(..., title='Uid')


class CredentialDiagnostics(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    credential_name: str | None = Field(None, title='Credential Name')
    credential_uid: str | None = Field(..., title='Credential Uid')
    detail: str = Field(..., title='Detail')
    referenced: bool = Field(..., title='Referenced')
    resolvable: bool = Field(..., title='Resolvable')
    source_uid: str = Field(..., title='Source Uid')


class CredentialRotation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    credential_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Credential Uid'
    )


class DataServerConnector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    connector_type: Literal['athena', 'bigquery', 'sql', 'table'] = Field(
        ..., title='Connector Type'
    )
    operations: list[Literal['select', 'describe', 'list']] | None = Field(
        None, title='Operations'
    )
    policy_version: str = Field(..., title='Policy Version')


class DataServerHeartbeat(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    last_heartbeat_at: str = Field(..., title='Last Heartbeat At')
    lease_seconds: int = Field(..., title='Lease Seconds')
    published_connectors: list[dict[str, Any]] | None = Field(
        None, title='Published Connectors'
    )
    state: Literal[
        'registering', 'ready', 'degraded', 'unavailable', 'draining', 'revoked'
    ] = Field(..., title='State')


class DataServerJobFailure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: constr(min_length=1) = Field(..., title='Code')
    message: constr(min_length=1) = Field(..., title='Message')


class DataServerRegister(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    connectors: list[DataServerConnector] | None = Field(None, title='Connectors')
    registration_identity: constr(min_length=1) = Field(
        ..., title='Registration Identity'
    )
    version: constr(min_length=1) = Field(..., title='Version')


class DataServerRegistration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    connectors: list[DataServerConnector] = Field(..., title='Connectors')
    identity_serial: str | None = Field(None, title='Identity Serial')
    identity_source: Literal['certificate', 'body'] = Field(
        ..., title='Identity Source'
    )
    last_heartbeat_at: str | None = Field(None, title='Last Heartbeat At')
    lease_seconds: int = Field(..., title='Lease Seconds')
    policy_version: str = Field(..., title='Policy Version')
    registered_at: str = Field(..., title='Registered At')
    registration_identity: str = Field(..., title='Registration Identity')
    source_uid: str = Field(..., title='Source Uid')
    state: Literal[
        'registering', 'ready', 'degraded', 'unavailable', 'draining', 'revoked'
    ] = Field(..., title='State')
    uid: str = Field(..., title='Uid')
    version: str | None = Field(None, title='Version')


class DataServerStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    connectors: list[DataServerConnector] = Field(..., title='Connectors')
    identity_expires_at: str | None = Field(None, title='Identity Expires At')
    identity_serial: str | None = Field(None, title='Identity Serial')
    last_heartbeat_at: str | None = Field(None, title='Last Heartbeat At')
    lease_seconds: int = Field(..., title='Lease Seconds')
    queue_depth: int = Field(..., title='Queue Depth')
    state: Literal[
        'registering', 'ready', 'degraded', 'unavailable', 'draining', 'revoked'
    ] = Field(..., title='State')


class DatasetConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    current_revision_uid: (
        constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None
    ) = Field(None, title='Current Revision Uid')
    kind: Literal['dataset'] = Field(..., title='Kind')
    license: str | None = Field(None, title='License')
    publication_eligible: bool | None = Field(False, title='Publication Eligible')
    schema_notes: str | None = Field(None, title='Schema Notes')
    tags: list[str] | None = Field(None, title='Tags')


class DatasetPublication(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actor_uid: str = Field(..., title='Actor Uid')
    created_at: str = Field(..., title='Created At')
    description: str | None = Field(None, title='Description')
    file_count: int = Field(..., title='File Count')
    license: str | None = Field(None, title='License')
    manifest_checksum: str = Field(..., title='Manifest Checksum')
    name: str = Field(..., title='Name')
    owner_uid: str = Field(..., title='Owner Uid')
    revision_uid: str = Field(..., title='Revision Uid')
    source_uid: str = Field(..., title='Source Uid')
    status: str = Field(..., title='Status')
    tags: list[str] | None = Field(None, title='Tags')
    total_size: int = Field(..., title='Total Size')
    uid: str = Field(..., title='Uid')
    unpublished_at: str | None = Field(None, title='Unpublished At')
    unpublished_by: str | None = Field(None, title='Unpublished By')


class DatasetPublicationCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    revision_uid: str = Field(..., title='Revision Uid')


class DatasetPublicationList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[DatasetPublication] = Field(..., title='Items')


class DatasetRevisionFile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    checksum: str = Field(..., title='Checksum')
    media_type: str = Field(..., title='Media Type')
    object_uid: str = Field(..., title='Object Uid')
    path: str = Field(..., title='Path')
    size: int = Field(..., title='Size')
    uid: str = Field(..., title='Uid')
    version_uid: str = Field(..., title='Version Uid')


class DatasetRevisionFileCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    object_uid: str | None = Field(None, title='Object Uid')
    path: str | None = Field(None, title='Path')
    source_path: str | None = Field(None, title='Source Path')
    source_uid: str | None = Field(None, title='Source Uid')
    version_uid: str | None = Field(None, title='Version Uid')


class DatasourceCapabilities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flight: bool = Field(..., title='Flight')
    https_fallback: Literal[True] = Field(True, title='Https Fallback')
    max_bytes: int = Field(..., title='Max Bytes')
    max_seconds: int = Field(..., title='Max Seconds')
    operations: list[Literal['select', 'describe', 'list']] = Field(
        ..., title='Operations'
    )
    row_limit: int = Field(..., title='Row Limit')
    streaming: Literal[True] = Field(True, title='Streaming')


class DatasourceColumn(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., title='Name')
    type: str = Field(..., title='Type')


class DatasourceConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allowed_operations: list[Literal['select', 'describe', 'list']] | None = Field(
        None, title='Allowed Operations'
    )
    connector_type: Literal['athena', 'bigquery', 'sql', 'table'] = Field(
        ..., title='Connector Type'
    )
    credential_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Credential Uid')
    )
    data_server_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Data Server Uid')
    )
    database_or_project: str | None = Field(None, title='Database Or Project')
    default_row_limit: conint(ge=1) | None = Field(10000, title='Default Row Limit')
    endpoint: str | None = Field(None, title='Endpoint')
    kind: Literal['datasource'] = Field(..., title='Kind')
    max_bytes: conint(ge=1) | None = Field(268435456, title='Max Bytes')
    max_seconds: conint(ge=1) | None = Field(300, title='Max Seconds')
    network_route: Literal['direct', 'dataserver'] | None = Field(
        'direct', title='Network Route'
    )


class DatasourceQueryCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    max_bytes: conint(ge=1) | None = Field(None, title='Max Bytes')
    max_seconds: conint(ge=1) | None = Field(None, title='Max Seconds')
    row_limit: conint(ge=1) | None = Field(None, title='Row Limit')
    sandbox_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Sandbox Uid')
    )
    sql: constr(min_length=1) = Field(..., title='Sql')


class DatasourceTable(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    columns: list[DatasourceColumn] | None = Field(None, title='Columns')
    name: str = Field(..., title='Name')


class DatasourceTest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    connector_type: str = Field(..., title='Connector Type')
    detail: str = Field(..., title='Detail')
    ok: bool = Field(..., title='Ok')


class DependencyStatusResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configured: bool = Field(..., title='Configured')
    detail: str = Field(..., title='Detail')
    name: str = Field(..., title='Name')
    ready: bool = Field(..., title='Ready')
    required: bool = Field(..., title='Required')


class EffectivePermissions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    effective_access_level: Literal['view', 'update', 'execute'] | None = Field(
        ..., title='Effective Access Level'
    )
    execute: bool = Field(..., title='Execute')
    is_owner: bool = Field(..., title='Is Owner')
    update: bool = Field(..., title='Update')
    view: bool = Field(..., title='View')


class EnvironmentBuildEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    destination_path: str = Field(..., title='Destination Path')
    sha256: constr(pattern=r'^[0-9a-f]{64}$') = Field(..., title='Sha256')
    size_bytes: conint(ge=0) = Field(..., title='Size Bytes')
    source_uri: str = Field(..., title='Source Uri')


class EnvironmentConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    build_entries: list[EnvironmentBuildEntry] | None = Field(
        None, title='Build Entries'
    )
    build_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Build Uid'
    )
    environment_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Environment Uid'
    )
    kind: Literal['environment'] = Field(..., title='Kind')
    resolved_provider_paths: dict[str, str] | None = Field(
        None, title='Resolved Provider Paths'
    )
    runtime_content_uids: (
        list[constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$')] | None
    ) = Field(None, title='Runtime Content Uids')


class FilesConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['files'] = Field(..., title='Kind')
    owning_user_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Owning User Uid'
    )
    quota_policy: str = Field(..., title='Quota Policy')
    storage_backend_id: str = Field(..., title='Storage Backend Id')
    versioning_policy: str = Field(..., title='Versioning Policy')


class FlightConnectivity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    detail: str = Field(..., title='Detail')
    endpoint: str | None = Field(None, title='Endpoint')
    reachable: bool = Field(..., title='Reachable')


class Grant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    access_level: Literal['view', 'update', 'execute'] = Field(
        ..., title='Access Level'
    )
    principal_kind: Literal['user', 'team', 'organization'] = Field(
        ..., title='Principal Kind'
    )
    principal_uid: str = Field(..., title='Principal Uid')
    uid: str | None = Field(None, title='Uid')


class HealthResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    service: Literal['contents'] = Field('contents', title='Service')
    status: Literal['healthy'] = Field('healthy', title='Status')
    success: Literal[True] = Field(True, title='Success')


class HomeFolderFileEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    is_directory: bool = Field(..., title='Is Directory')
    modified_at: str | None = Field(None, title='Modified At')
    name: str = Field(..., title='Name')
    path: str = Field(..., title='Path')
    scope: str | None = Field(None, title='Scope')
    size: int = Field(..., title='Size')
    title: str | None = Field(None, title='Title')


class HomeFolderFileList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[HomeFolderFileEntry] = Field(..., title='Items')
    path: str = Field(..., title='Path')


class HomeFolderQuota(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    limit_bytes: int = Field(..., title='Limit Bytes')
    limit_objects: int = Field(..., title='Limit Objects')
    reserved_bytes: int = Field(..., title='Reserved Bytes')
    reserved_objects: int = Field(..., title='Reserved Objects')
    used_bytes: int = Field(..., title='Used Bytes')
    used_objects: int = Field(..., title='Used Objects')


class HttpsConnectivity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    detail: str = Field(..., title='Detail')
    reachable: bool = Field(..., title='Reachable')
    url: str | None = Field(None, title='Url')


class IssuedIdentity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ca_certificate: str = Field(..., title='Ca Certificate')
    certificate: str = Field(..., title='Certificate')
    expires_at: str = Field(..., title='Expires At')
    serial: str = Field(..., title='Serial')


class ManifestEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    blocks: list[str] | None = Field(None, title='Blocks')
    checksum: constr(pattern=r'^[0-9a-f]{64}$') = Field(..., title='Checksum')
    modified_at: str = Field(..., title='Modified At')
    path: str = Field(..., title='Path')
    size: conint(ge=0) = Field(..., title='Size')


class ManifestPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    block_size: int | None = Field(4194304, title='Block Size')
    entries: list[ManifestEntry] | None = Field(None, title='Entries')
    tombstones: dict[str, str] | None = Field(None, title='Tombstones')


class McpApproval(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actor_uid: str = Field(..., title='Actor Uid')
    arguments_hash: str = Field(..., title='Arguments Hash')
    arguments_redacted: dict[str, Any] = Field(..., title='Arguments Redacted')
    call_uid: str = Field(..., title='Call Uid')
    created_at: str = Field(..., title='Created At')
    decided_at: str | None = Field(None, title='Decided At')
    decided_by: str | None = Field(None, title='Decided By')
    destination_uri: str | None = Field(None, title='Destination Uri')
    expires_at: str = Field(..., title='Expires At')
    note: str | None = Field(None, title='Note')
    session_uid: str = Field(..., title='Session Uid')
    source_uid: str = Field(..., title='Source Uid')
    status: Literal['pending', 'approved', 'rejected', 'expired', 'consumed'] = Field(
        ..., title='Status'
    )
    tool: str = Field(..., title='Tool')
    uid: str = Field(..., title='Uid')


class McpApprovalDecision(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    note: constr(max_length=2000) | None = Field(None, title='Note')


class McpApprovalList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[McpApproval] = Field(..., title='Items')


class McpArtifactView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    destination_uri: str | None = Field(None, title='Destination Uri')
    media_type: str | None = Field(None, title='Media Type')
    name: str = Field(..., title='Name')
    object_uid: str | None = Field(None, title='Object Uid')
    operation_uid: str | None = Field(None, title='Operation Uid')
    size: int | None = Field(None, title='Size')
    source_uri: str | None = Field(None, title='Source Uri')
    transfer_uid: str | None = Field(None, title='Transfer Uid')
    url: str | None = Field(None, title='Url')
    version_uid: str | None = Field(None, title='Version Uid')


class McpCallCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    arguments: dict[str, Any] | None = Field(None, title='Arguments')
    destination_uri: str | None = Field(None, title='Destination Uri')
    tool: constr(min_length=1) = Field(..., title='Tool')


class McpCallError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str = Field(..., title='Code')
    message: str = Field(..., title='Message')


class McpCallResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifacts: list[McpArtifactView] | None = Field(None, title='Artifacts')
    content: list[dict[str, Any]] | None = Field(None, title='Content')


class McpConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allowed_destinations: list[str] | None = Field(None, title='Allowed Destinations')
    allowed_domains: list[str] | None = Field(None, title='Allowed Domains')
    allowed_media_types: list[str] | None = Field(None, title='Allowed Media Types')
    allowed_resources: list[str] | None = Field(None, title='Allowed Resources')
    allowed_tools: list[str] | None = Field(None, title='Allowed Tools')
    approval_policy: Literal['explicit', 'auto-allowlisted', 'never'] = Field(
        ..., title='Approval Policy'
    )
    credential_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Credential Uid')
    )
    destination_policy: Literal['allowlist', 'home-folder-only', 'dataset-only'] = (
        Field(..., title='Destination Policy')
    )
    endpoint: str | None = Field(None, title='Endpoint')
    kind: Literal['mcp'] = Field(..., title='Kind')
    managed_server_uid: (
        constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None
    ) = Field(None, title='Managed Server Uid')
    max_result_bytes: conint(ge=1) | None = Field(67108864, title='Max Result Bytes')
    transport: Literal['stdio', 'streamable-http', 'sse'] = Field(
        ..., title='Transport'
    )


class McpHealth(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    detail: str = Field(..., title='Detail')
    ok: bool = Field(..., title='Ok')
    transport: str = Field(..., title='Transport')


class McpResourceView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    media_type: str | None = Field(None, title='Media Type')
    name: str | None = Field(None, title='Name')
    uri: str = Field(..., title='Uri')


class McpSession(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actor_uid: str = Field(..., title='Actor Uid')
    allowed_destinations: list[str] = Field(..., title='Allowed Destinations')
    allowed_domains: list[str] = Field(..., title='Allowed Domains')
    allowed_resources: list[str] = Field(..., title='Allowed Resources')
    allowed_tools: list[str] = Field(..., title='Allowed Tools')
    approval_policy: Literal['explicit', 'auto-allowlisted', 'never'] = Field(
        ..., title='Approval Policy'
    )
    created_at: str = Field(..., title='Created At')
    destination_policy: Literal['allowlist', 'home-folder-only', 'dataset-only'] = (
        Field(..., title='Destination Policy')
    )
    expires_at: str = Field(..., title='Expires At')
    max_result_bytes: int = Field(..., title='Max Result Bytes')
    sandbox_uid: str | None = Field(None, title='Sandbox Uid')
    source_uid: str = Field(..., title='Source Uid')
    status: Literal['active', 'revoked', 'expired'] = Field(..., title='Status')
    uid: str = Field(..., title='Uid')


class McpSessionCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expires_in: conint(ge=1) | None = Field(None, title='Expires In')
    sandbox_uid: str | None = Field(None, title='Sandbox Uid')
    source_uid: constr(min_length=1) = Field(..., title='Source Uid')
    tools: list[str] | None = Field(None, title='Tools')


class McpSessionList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[McpSession] = Field(..., title='Items')


class McpToolView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = Field(None, title='Description')
    input_schema: dict[str, Any] | None = Field(None, title='Input Schema')
    name: str = Field(..., title='Name')


class MountSession(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    access_key_id: str = Field(..., title='Access Key Id')
    endpoint_url: str | None = Field('', title='Endpoint Url')
    expiration: str = Field(..., title='Expiration')
    region: str | None = Field('', title='Region')
    secret_access_key: str = Field(..., title='Secret Access Key')
    session_token: str = Field(..., title='Session Token')


class MountSessionAnswer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mount_session: MountSession | None = None


class ObjectList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[ContentObject] = Field(..., title='Items')
    next_cursor: str | None = Field(None, title='Next Cursor')


class OperationCapability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    available: bool = Field(..., title='Available')
    deployed: bool = Field(..., title='Deployed')
    documentation: str | None = Field(None, title='Documentation')
    kind: Literal['operation'] = Field('operation', title='Kind')
    label: str = Field(..., title='Label')
    name: str = Field(..., title='Name')
    reason: str | None = Field(None, title='Reason')


class OperationView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: int = Field(..., title='Attempt')
    cancellation_requested: bool = Field(..., title='Cancellation Requested')
    completed_at: str | None = Field(None, title='Completed At')
    created_at: str = Field(..., title='Created At')
    error_code: str | None = Field(None, title='Error Code')
    error_message: str | None = Field(None, title='Error Message')
    max_attempts: int = Field(..., title='Max Attempts')
    operation_kind: str = Field(..., title='Operation Kind')
    result: dict[str, Any] | None = Field(None, title='Result')
    source_uid: str | None = Field(None, title='Source Uid')
    status: Literal[
        'pending', 'running', 'succeeded', 'failed', 'cancelling', 'cancelled'
    ] = Field(..., title='Status')
    uid: str = Field(..., title='Uid')
    updated_at: str = Field(..., title='Updated At')


class PartWritten(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bytes_written: int = Field(..., title='Bytes Written')
    part: str = Field(..., title='Part')


class PingResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: Literal['Pong.'] = Field('Pong.', title='Message')
    success: Literal[True] = Field(True, title='Success')
    version: str = Field(..., title='Version')


class PlanAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    blocks: list[int] | None = Field(None, title='Blocks')
    kind: Literal['upload', 'download', 'delete_remote', 'delete_local', 'conflict'] = (
        Field(..., title='Kind')
    )
    object_uid: str | None = Field(None, title='Object Uid')
    path: str = Field(..., title='Path')
    reason: str = Field(..., title='Reason')
    version_uid: str | None = Field(None, title='Version Uid')


class PresignedAccess(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expires_in: int = Field(..., title='Expires In')
    operation: Literal['get', 'put'] = Field(..., title='Operation')
    path: str = Field(..., title='Path')
    url: str = Field(..., title='Url')


class PublishTableRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    relation: str = Field(
        ...,
        description="What the table is called. One segment, and the name a query uses — never a path: the directory is derived from the publishing root, so publishing cannot name somebody else's file.",
        title='Relation',
    )


class PublishTableReservation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    directory: str = Field(..., title='Directory')
    first_part: str = Field(..., title='First Part')
    owner_uid: str = Field(..., title='Owner Uid')
    relation: str = Field(..., title='Relation')


class PublishedTableView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    datasource: dict[str, Any] = Field(..., title='Datasource')
    owner_uid: str = Field(..., title='Owner Uid')
    parts: int = Field(..., title='Parts')
    relation: str = Field(..., title='Relation')


class QuarantineRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reason: str = Field(..., title='Reason')


class QueryError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str = Field(..., title='Code')
    message: str = Field(..., title='Message')


class QueryLimits(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bytes: conint(ge=1) = Field(..., title='Bytes')
    rows: conint(ge=1) = Field(..., title='Rows')
    seconds: conint(ge=1) = Field(..., title='Seconds')


class QueryResultReference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    checksum: str = Field(..., title='Checksum')
    media_type: str | None = Field(
        'application/vnd.apache.arrow.stream', title='Media Type'
    )
    object_uid: str = Field(..., title='Object Uid')
    version_uid: str = Field(..., title='Version Uid')


class QuerySave(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dataset_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Dataset Uid'
    )
    path: constr(min_length=1) = Field(..., title='Path')


class ReadinessResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dependencies: list[DependencyStatusResponse] = Field(..., title='Dependencies')
    service: Literal['contents'] = Field('contents', title='Service')
    status: Literal['ready', 'not-ready'] = Field(..., title='Status')
    success: bool = Field(..., title='Success')


class ReconcileReportView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    duration_seconds: float = Field(..., title='Duration Seconds')
    error: str | None = Field(None, title='Error')
    ran_at: str = Field(..., title='Ran At')
    report: dict[str, Any] | None = Field(None, title='Report')
    sample: int = Field(..., title='Sample')
    verify: bool = Field(..., title='Verify')


class RestoreRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version_uid: str = Field(..., title='Version Uid')


class ServiceStatusResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    caller: CallerResponse
    service: Literal['contents'] = Field('contents', title='Service')
    success: Literal[True] = Field(True, title='Success')
    version: str = Field(..., title='Version')


class Sharing(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    grants: list[Grant] | None = Field(None, title='Grants')


class SourceKindCapability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    available: bool = Field(..., title='Available')
    count: int = Field(..., title='Count')
    creatable: bool = Field(..., title='Creatable')
    deployed: bool = Field(..., title='Deployed')
    documentation: str | None = Field(None, title='Documentation')
    kind: str = Field(..., title='Kind')
    label: str = Field(..., title='Label')
    name: str = Field(..., title='Name')
    reason: str | None = Field(None, title='Reason')


class SpaceRelease(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attachments_revoked: int = Field(..., title='Attachments Revoked')
    released: list[str] = Field(..., title='Released')
    space_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Space Uid'
    )


class SyncBlockView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    checksum: str = Field(..., title='Checksum')
    index: int = Field(..., title='Index')
    path: str = Field(..., title='Path')
    session_uid: str = Field(..., title='Session Uid')
    size: int = Field(..., title='Size')


class SyncCompose(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    base_version_uid: str = Field(..., title='Base Version Uid')
    blocks: list[str] | None = Field(None, title='Blocks')
    checksum: constr(pattern=r'^[0-9a-f]{64}$') = Field(..., title='Checksum')
    media_type: str | None = Field('application/octet-stream', title='Media Type')
    path: str = Field(..., title='Path')
    size: conint(ge=0) = Field(..., title='Size')


class SyncConflictView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    created_at: str = Field(..., title='Created At')
    local_entry: ManifestEntry | None = None
    path: str = Field(..., title='Path')
    reason: str = Field(..., title='Reason')
    remote_entry: ManifestEntry | None = None
    resolution: Literal['local', 'remote', 'keep-both'] | None = Field(
        None, title='Resolution'
    )
    resolved_at: str | None = Field(None, title='Resolved At')
    session_uid: str = Field(..., title='Session Uid')
    status: Literal['open', 'resolved'] = Field(..., title='Status')
    uid: str = Field(..., title='Uid')


class SyncCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    block_size: int | None = Field(4194304, title='Block Size')
    conflict_policy: Literal['manual', 'newest', 'local', 'remote'] | None = Field(
        'manual', title='Conflict Policy'
    )
    delete: bool | None = Field(False, title='Delete')
    direction: Literal['push', 'pull', 'bidirectional'] | None = Field(
        'bidirectional', title='Direction'
    )
    exclusions: list[str] | None = Field(None, title='Exclusions')
    local_manifest: ManifestPayload
    remote_uri: str = Field(..., title='Remote Uri')
    watch: bool | None = Field(False, title='Watch')


class SyncPlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actions: list[PlanAction] | None = Field(None, title='Actions')


class SyncReconcile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    local_manifest: ManifestPayload


class SyncReport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    applied: list[str] | None = Field(None, title='Applied')
    failed: dict[str, str] | None = Field(None, title='Failed')
    transferred_bytes: conint(ge=0) | None = Field(0, title='Transferred Bytes')


class SyncSessionView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    block_size: int = Field(..., title='Block Size')
    completed_at: str | None = Field(None, title='Completed At')
    conflict_count: int = Field(..., title='Conflict Count')
    conflict_policy: str = Field(..., title='Conflict Policy')
    created_at: str = Field(..., title='Created At')
    delete: bool = Field(..., title='Delete')
    deleted_files: int = Field(..., title='Deleted Files')
    direction: str = Field(..., title='Direction')
    downloaded_files: int = Field(..., title='Downloaded Files')
    error_code: str | None = Field(None, title='Error Code')
    error_message: str | None = Field(None, title='Error Message')
    exclusions: list[str] = Field(..., title='Exclusions')
    last_heartbeat_at: str | None = Field(None, title='Last Heartbeat At')
    plan: SyncPlan | None = None
    reconciliations: int = Field(..., title='Reconciliations')
    remote_uri: str = Field(..., title='Remote Uri')
    source_uid: str = Field(..., title='Source Uid')
    status: str = Field(..., title='Status')
    transferred_bytes: int = Field(..., title='Transferred Bytes')
    uid: str = Field(..., title='Uid')
    updated_at: str = Field(..., title='Updated At')
    uploaded_files: int = Field(..., title='Uploaded Files')
    watch: bool = Field(..., title='Watch')


class TicketResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    checksum: str = Field(..., title='Checksum')
    size: int = Field(..., title='Size')
    storage_key: str = Field(..., title='Storage Key')


class TicketValidation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ticket: constr(min_length=1) = Field(..., title='Ticket')


class TransferCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    checksum: constr(pattern=r'^[0-9a-f]{64}$') = Field(..., title='Checksum')
    destination_uri: str = Field(..., title='Destination Uri')
    direction: Literal['upload'] = Field('upload', title='Direction')
    media_type: str | None = Field('application/octet-stream', title='Media Type')
    overwrite: Literal['reject', 'replace', 'new-version'] | None = Field(
        'reject', title='Overwrite'
    )
    size: conint(ge=0) = Field(..., title='Size')


class TransferPart(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    checksum: str = Field(..., title='Checksum')
    number: int = Field(..., title='Number')
    size: int = Field(..., title='Size')


class TransferView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    completed_at: str | None = Field(None, title='Completed At')
    created_at: str = Field(..., title='Created At')
    destination_uri: str | None = Field(None, title='Destination Uri')
    direction: str = Field(..., title='Direction')
    error_code: str | None = Field(None, title='Error Code')
    error_message: str | None = Field(None, title='Error Message')
    expected_checksum: str = Field(..., title='Expected Checksum')
    expected_size: int = Field(..., title='Expected Size')
    media_type: str = Field(..., title='Media Type')
    object_uid: str | None = Field(None, title='Object Uid')
    overwrite_policy: str = Field(..., title='Overwrite Policy')
    part_count: int = Field(..., title='Part Count')
    parts: list[TransferPart] | None = Field(None, title='Parts')
    path: str = Field(..., title='Path')
    received_bytes: int = Field(..., title='Received Bytes')
    source_uid: str = Field(..., title='Source Uid')
    source_uri: str | None = Field(None, title='Source Uri')
    status: str = Field(..., title='Status')
    uid: str = Field(..., title='Uid')
    updated_at: str = Field(..., title='Updated At')
    version_uid: str | None = Field(None, title='Version Uid')


class ValidationError(BaseModel):
    ctx: dict[str, Any] | None = Field(None, title='Context')
    input: Any | None = Field(None, title='Input')
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class VersionList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[ContentObjectVersion] = Field(..., title='Items')
    next_cursor: str | None = Field(None, title='Next Cursor')


class VolumeConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    access_modes: list[Literal['ro', 'rw']] = Field(..., title='Access Modes')
    backing_resource_id: str | None = Field(None, title='Backing Resource Id')
    capacity_bytes: conint(ge=1) = Field(..., title='Capacity Bytes')
    concurrent_readers: bool = Field(..., title='Concurrent Readers')
    concurrent_writers: bool = Field(..., title='Concurrent Writers')
    default_mount_path: str = Field(..., title='Default Mount Path')
    kind: Literal['volume'] = Field(..., title='Kind')
    scope: Literal['user', 'space'] = Field(..., title='Scope')
    storage_class: str | None = Field(None, title='Storage Class')


class AttachmentError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Literal[
        'UNAUTHENTICATED',
        'FORBIDDEN',
        'NOT_FOUND',
        'CONFLICT',
        'QUOTA_EXCEEDED',
        'CAPABILITY_UNAVAILABLE',
        'CHECKSUM_MISMATCH',
        'PROVIDER_UNAVAILABLE',
        'CAPABILITY_REVOKED',
        'OPERATION_CANCELLED',
        'INTERNAL_ERROR',
    ] = Field(..., title='StableErrorCode')
    message: str = Field(..., title='Message')
    retryable: bool = Field(..., title='Retryable')


class AttachmentStatusUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capabilities: (
        list[
            Literal[
                'browse',
                'transfer',
                'mount',
                'query',
                'materialize',
                'sync',
                'local-bridge-mount',
            ]
        ]
        | None
    ) = Field(None, title='Capabilities')
    error: AttachmentError | None = None
    provider_resource_id: str | None = Field(None, title='Provider Resource Id')
    status: Literal['ready', 'degraded', 'failed', 'revoked'] = Field(
        ..., title='Status'
    )


class BridgeHeartbeat(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bridge: BridgeSession
    client_token: str = Field(..., title='Client Token')


class BridgeList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[BridgeSession] = Field(..., title='Items')


class BridgeOpened(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bridge: BridgeSession
    client_token: str = Field(..., title='Client Token')
    relay_url: str = Field(..., title='Relay Url')
    session_key: str = Field(..., title='Session Key')


class CapabilityTicketClaims(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actor_uid: str = Field(..., title='Actor Uid')
    exp: int = Field(..., title='Exp')
    jti: str = Field(..., title='Jti')
    limits: QueryLimits
    operation: Literal['get'] = Field(..., title='Operation')
    policy_version: str = Field(..., title='Policy Version')
    query_uid: str = Field(..., title='Query Uid')
    sandbox_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Sandbox Uid')
    )
    source_uid: str = Field(..., title='Source Uid')


class CloudObjectList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[CloudObjectView] = Field(..., title='Items')
    next_cursor: str | None = Field(None, title='Next Cursor')


class ContentAttachment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    access_mode: Literal['mount', 'python', 'object-client'] | None = Field(
        None, title='Access Mode'
    )
    capabilities: (
        list[
            Literal[
                'browse',
                'transfer',
                'mount',
                'query',
                'materialize',
                'sync',
                'local-bridge-mount',
            ]
        ]
        | None
    ) = Field(None, title='Capabilities')
    cleanup_policy: (
        Literal['revoke', 'remove-materialization', 'retain-source'] | None
    ) = Field('revoke', title='Cleanup Policy')
    created_at: AwareDatetime = Field(..., title='Created At')
    delivery: Literal[
        'mount', 'local-bridge', 'materialize', 'client', 'environment'
    ] = Field(..., title='Delivery')
    error: AttachmentError | None = None
    expires_at: AwareDatetime | None = Field(None, title='Expires At')
    fallback_reason: str | None = Field(None, title='Fallback Reason')
    filesystem_primitives: (
        list[
            Literal[
                'list', 'stat', 'read', 'write', 'mkdir', 'remove', 'upload', 'download'
            ]
        ]
        | None
    ) = Field(None, title='Filesystem Primitives')
    last_seen_at: AwareDatetime | None = Field(None, title='Last Seen At')
    limits: AttachmentLimits | None = None
    mode: Literal['ro', 'rw'] = Field(..., title='Mode')
    mount_path: str | None = Field(None, title='Mount Path')
    provider_resource_id: str | None = Field(None, title='Provider Resource Id')
    ready_at: AwareDatetime | None = Field(None, title='Ready At')
    required: bool | None = Field(True, title='Required')
    revision_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Revision Uid')
    )
    revoked_at: AwareDatetime | None = Field(None, title='Revoked At')
    sandbox_provider: str = Field(..., title='Sandbox Provider')
    sandbox_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Sandbox Uid'
    )
    source_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Source Uid'
    )
    status: Literal[
        'requested', 'preparing', 'ready', 'degraded', 'revoking', 'revoked', 'failed'
    ] = Field(..., title='AttachmentStatus')
    token_audience: str | None = Field(None, title='Token Audience')
    uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Uid'
    )


class ContentAttachmentManifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attachments: list[ContentAttachment] = Field(..., title='Attachments')
    contract_version: Literal['v1'] = Field(..., title='Contract Version')
    generated_at: AwareDatetime = Field(..., title='Generated At')
    sandbox_provider: str = Field(..., title='Sandbox Provider')
    sandbox_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Sandbox Uid'
    )


class ContentsCapabilities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    counts_truncated: bool = Field(..., title='Counts Truncated')
    operations: list[OperationCapability] = Field(..., title='Operations')
    source_kinds: list[SourceKindCapability] = Field(..., title='Source Kinds')


class DataServerConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    connectors: list[DataServerConnector] | None = Field(None, title='Connectors')
    identity_expires_at: AwareDatetime | None = Field(None, title='Identity Expires At')
    identity_serial: str | None = Field(None, title='Identity Serial')
    kind: Literal['data-server'] = Field(..., title='Kind')
    last_heartbeat_at: AwareDatetime | None = Field(None, title='Last Heartbeat At')
    lease_seconds: conint(ge=5) | None = Field(None, title='Lease Seconds')
    managed: bool | None = Field(False, title='Managed')
    mtls_issuer: str = Field(..., title='Mtls Issuer')
    policy_version: str = Field(..., title='Policy Version')
    previous_identity_serial: str | None = Field(None, title='Previous Identity Serial')
    registration_identity: str = Field(..., title='Registration Identity')
    state: (
        Literal[
            'registering', 'ready', 'degraded', 'unavailable', 'draining', 'revoked'
        ]
        | None
    ) = Field('registering', title='State')
    version: str | None = Field(None, title='Version')


class DataServerConnectivity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    detail: str = Field(..., title='Detail')
    flight: FlightConnectivity
    https_fallback: HttpsConnectivity
    ok: bool = Field(..., title='Ok')


class DataServerJob(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    connector: str | None = Field(None, title='Connector')
    connector_type: Literal['athena', 'bigquery', 'sql', 'table'] = Field(
        ..., title='Connector Type'
    )
    credential_ref: str | None = Field(None, title='Credential Ref')
    limits: QueryLimits
    policy_version: str = Field(..., title='Policy Version')
    query_uid: str = Field(..., title='Query Uid')
    sql: str = Field(..., title='Sql')


class DataServerJobs(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cancel: list[str] = Field(..., title='Cancel')
    jobs: list[DataServerJob] = Field(..., title='Jobs')


class DataServerRegistered(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    jobs_url: str = Field(..., title='Jobs Url')
    registration: DataServerRegistration


class DatasetRevision(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actor_uid: str = Field(..., title='Actor Uid')
    created_at: str = Field(..., title='Created At')
    file_count: int = Field(..., title='File Count')
    files: list[DatasetRevisionFile] | None = Field(None, title='Files')
    manifest_checksum: str = Field(..., title='Manifest Checksum')
    origin_kind: str = Field(..., title='Origin Kind')
    source_uid: str = Field(..., title='Source Uid')
    status: str = Field(..., title='Status')
    total_size: int = Field(..., title='Total Size')
    uid: str = Field(..., title='Uid')


class DatasetRevisionCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    files: list[DatasetRevisionFileCreate] = Field(..., min_length=1, title='Files')
    origin_kind: Literal[
        'upload',
        'home-folder',
        'sandbox-result',
        'cloud-storage',
        'volume',
        'acquisition',
    ] = Field(..., title='Origin Kind')


class DatasetRevisionList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[DatasetRevision] = Field(..., title='Items')


class DatasourceQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actor_uid: str = Field(..., title='Actor Uid')
    bytes: int | None = Field(None, title='Bytes')
    created_at: str = Field(..., title='Created At')
    data_server_uid: str | None = Field(None, title='Data Server Uid')
    error: QueryError | None = None
    finished_at: str | None = Field(None, title='Finished At')
    max_bytes: int = Field(..., title='Max Bytes')
    max_seconds: int = Field(..., title='Max Seconds')
    operation_uid: str | None = Field(None, title='Operation Uid')
    policy_version: str = Field(..., title='Policy Version')
    result: QueryResultReference | None = None
    row_limit: int = Field(..., title='Row Limit')
    rows: int | None = Field(None, title='Rows')
    sandbox_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Sandbox Uid')
    )
    source_uid: str = Field(..., title='Source Uid')
    sql_hash: str = Field(..., title='Sql Hash')
    started_at: str | None = Field(None, title='Started At')
    status: Literal['pending', 'running', 'succeeded', 'failed', 'cancelled'] = Field(
        ..., title='Status'
    )
    truncated: str | None = Field(None, title='Truncated')
    uid: str = Field(..., title='Uid')


class DatasourceQueryList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[DatasourceQuery] = Field(..., title='Items')
    next_cursor: str | None = Field(None, title='Next Cursor')


class DatasourceSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    discovered_at: str = Field(..., title='Discovered At')
    tables: list[DatasourceTable] = Field(..., title='Tables')


class DeadLetterList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[OperationView] = Field(..., title='Items')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class McpCall(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approval_uid: str | None = Field(None, title='Approval Uid')
    arguments_hash: str = Field(..., title='Arguments Hash')
    arguments_redacted: dict[str, Any] = Field(..., title='Arguments Redacted')
    completed_at: str | None = Field(None, title='Completed At')
    created_at: str = Field(..., title='Created At')
    destination_uri: str | None = Field(None, title='Destination Uri')
    error: McpCallError | None = None
    operation_uid: str | None = Field(None, title='Operation Uid')
    result: McpCallResult | None = None
    session_uid: str = Field(..., title='Session Uid')
    status: Literal[
        'pending-approval',
        'approved',
        'denied',
        'running',
        'succeeded',
        'failed',
        'refused',
    ] = Field(..., title='Status')
    tool: str = Field(..., title='Tool')
    uid: str = Field(..., title='Uid')
    updated_at: str = Field(..., title='Updated At')


class McpCallList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[McpCall] = Field(..., title='Items')


class McpToolManifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    discovered_at: str = Field(..., title='Discovered At')
    resources: list[McpResourceView] = Field(..., title='Resources')
    tools: list[McpToolView] = Field(..., title='Tools')


class PreparedAttachment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    access_mode: Literal['mount', 'python', 'object-client'] | None = Field(
        None, title='Access Mode'
    )
    bridge: BridgeMountGrant | None = None
    capabilities: (
        list[
            Literal[
                'browse',
                'transfer',
                'mount',
                'query',
                'materialize',
                'sync',
                'local-bridge-mount',
            ]
        ]
        | None
    ) = Field(None, title='Capabilities')
    cleanup_policy: (
        Literal['revoke', 'remove-materialization', 'retain-source'] | None
    ) = Field('revoke', title='Cleanup Policy')
    created_at: AwareDatetime = Field(..., title='Created At')
    delivery: Literal[
        'mount', 'local-bridge', 'materialize', 'client', 'environment'
    ] = Field(..., title='Delivery')
    error: AttachmentError | None = None
    expires_at: AwareDatetime | None = Field(None, title='Expires At')
    fallback_reason: str | None = Field(None, title='Fallback Reason')
    filesystem_primitives: (
        list[
            Literal[
                'list', 'stat', 'read', 'write', 'mkdir', 'remove', 'upload', 'download'
            ]
        ]
        | None
    ) = Field(None, title='Filesystem Primitives')
    last_seen_at: AwareDatetime | None = Field(None, title='Last Seen At')
    limits: AttachmentLimits | None = None
    mode: Literal['ro', 'rw'] = Field(..., title='Mode')
    mount_path: str | None = Field(None, title='Mount Path')
    mount_session: MountSession | None = None
    provider_resource_id: str | None = Field(None, title='Provider Resource Id')
    ready_at: AwareDatetime | None = Field(None, title='Ready At')
    required: bool | None = Field(True, title='Required')
    revision_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Revision Uid')
    )
    revoked_at: AwareDatetime | None = Field(None, title='Revoked At')
    sandbox_provider: str = Field(..., title='Sandbox Provider')
    sandbox_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Sandbox Uid'
    )
    source_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Source Uid'
    )
    status: Literal[
        'requested', 'preparing', 'ready', 'degraded', 'revoking', 'revoked', 'failed'
    ] = Field(..., title='AttachmentStatus')
    token_audience: str | None = Field(None, title='Token Audience')
    uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Uid'
    )


class SyncConflictList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[SyncConflictView] = Field(..., title='Items')


class SyncSessionList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[SyncSessionView] = Field(..., title='Items')
    next_cursor: str | None = Field(None, title='Next Cursor')


class TicketValidationResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    claims: CapabilityTicketClaims | None = None
    reason: str | None = Field(None, title='Reason')
    result: TicketResult | None = None
    valid: bool = Field(..., title='Valid')


class TransferList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[TransferView] = Field(..., title='Items')
    next_cursor: str | None = Field(None, title='Next Cursor')


class AttachmentList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[ContentAttachment] = Field(..., title='Items')


class ContentSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capabilities: (
        list[
            Literal[
                'browse',
                'transfer',
                'mount',
                'query',
                'materialize',
                'sync',
                'local-bridge-mount',
            ]
        ]
        | None
    ) = Field(None, title='Capabilities')
    configuration: (
        FilesConfiguration
        | DatasetConfiguration
        | VolumeConfiguration
        | CloudStorageConfiguration
        | DatasourceConfiguration
        | DataServerConfiguration
        | McpConfiguration
        | EnvironmentConfiguration
    ) = Field(..., discriminator='kind', title='Configuration')
    contract_version: Literal['v1'] = Field(..., title='Contract Version')
    created_at: AwareDatetime = Field(..., title='Created At')
    credential_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Credential Uid')
    )
    description: str | None = Field(None, title='Description')
    kind: Literal[
        'files',
        'dataset',
        'volume',
        'cloud-storage',
        'datasource',
        'data-server',
        'mcp',
        'environment',
    ] = Field(..., title='Kind')
    name: constr(min_length=1) = Field(..., title='Name')
    principal_kind: Literal['user', 'team', 'organization'] = Field(
        ..., title='PrincipalKind'
    )
    principal_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Principal Uid'
    )
    space_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = Field(
        None, title='Space Uid'
    )
    status: Literal['pending', 'ready', 'degraded', 'disabled', 'failed'] = Field(
        ..., title='SourceStatus'
    )
    uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') = Field(
        ..., title='Uid'
    )
    updated_at: AwareDatetime = Field(..., title='Updated At')


class ContentSourceCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capabilities: (
        list[
            Literal[
                'browse',
                'transfer',
                'mount',
                'query',
                'materialize',
                'sync',
                'local-bridge-mount',
            ]
        ]
        | None
    ) = Field(None, title='Capabilities')
    configuration: (
        FilesConfiguration
        | DatasetConfiguration
        | VolumeConfiguration
        | CloudStorageConfiguration
        | DatasourceConfiguration
        | DataServerConfiguration
        | McpConfiguration
        | EnvironmentConfiguration
    ) = Field(..., discriminator='kind', title='Configuration')
    credential_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Credential Uid')
    )
    description: str | None = Field(None, title='Description')
    kind: Literal[
        'files',
        'dataset',
        'volume',
        'cloud-storage',
        'datasource',
        'data-server',
        'mcp',
        'environment',
    ] = Field(..., title='Kind')
    name: constr(min_length=1) = Field(..., title='Name')
    principal_kind: Literal['user', 'team', 'organization'] | None = None
    principal_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Principal Uid')
    )
    space_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = Field(
        None, title='Space Uid'
    )


class ContentSourceUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capabilities: (
        list[
            Literal[
                'browse',
                'transfer',
                'mount',
                'query',
                'materialize',
                'sync',
                'local-bridge-mount',
            ]
        ]
        | None
    ) = Field(None, title='Capabilities')
    configuration: (
        FilesConfiguration
        | DatasetConfiguration
        | VolumeConfiguration
        | CloudStorageConfiguration
        | DatasourceConfiguration
        | DataServerConfiguration
        | McpConfiguration
        | EnvironmentConfiguration
        | None
    ) = Field(None, title='Configuration')
    credential_uid: constr(pattern=r'^[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}$') | None = (
        Field(None, title='Credential Uid')
    )
    description: str | None = Field(None, title='Description')
    name: constr(min_length=1) | None = Field(None, title='Name')
    status: Literal['pending', 'ready', 'degraded', 'disabled', 'failed'] | None = None


class CatalogSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    permissions: EffectivePermissions
    source: ContentSource


class SourceList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[CatalogSource] = Field(..., title='Items')
    next_cursor: str | None = Field(None, title='Next Cursor')
