/*
 * Copyright (c) 2023-2025 Datalayer, Inc.
 * Distributed under the terms of the Modified BSD License.
 */

/**
 * Node.js-safe entry point for @datalayer/core.
 *
 * Exports only the client, models, API, and services modules.
 * Excludes React components, views, hooks, navigation, otel UI,
 * state, utils, and collaboration modules that depend on browser
 * APIs, React, or CSS imports incompatible with Node.js ESM.
 *
 * Use this entry point in VS Code extensions, CLI tools, and
 * server-side code.
 *
 * @example
 * ```typescript
 * import { DatalayerClient } from "@datalayer/core/lib/node";
 * ```
 */

// Services (no React/CSS dependencies)
export * from './services';

// Export APIs
export {
  requestDatalayerAPI,
  RunResponseError,
  NetworkError,
} from './api/DatalayerApi';
export type { IRequestDatalayerAPIOptions } from './api/DatalayerApi';
export { API_BASE_PATHS } from './api/constants';
export * as aiAgentsApi from './api/ai-agents';
export * as runtimesApi from './api/runtimes';
export * as iamApi from './api/iam';
export * as spacerApi from './api/spacer';

// Export client, models, and types
export {
  DatalayerClient,
  type DatalayerClientConfig,
  type ClientHandlers,
  User,
  Runtime,
  Environment,
  Snapshot,
  Space,
  Notebook,
  LexicalDTO,
  Secret,
  Credits,
  Item,
  type RuntimeJSON,
  type EnvironmentJSON,
  type UserJSON,
  type RuntimeData,
  type EnvironmentData,
  type UserData,
  type SpaceData,
  type SpaceItem,
  type NotebookData,
  type LexicalData,
  type RuntimeSnapshotData,
  type CreditsInfo,
  type CreditReservation,
  type CreateRuntimeRequest,
  type CreateRuntimeResponse,
  type ListRuntimesResponse,
  type ListEnvironmentsResponse,
  type CreateRuntimeSnapshotRequest,
  type CreateRuntimeSnapshotResponse,
  type GetRuntimeSnapshotResponse,
  type ListRuntimeSnapshotsResponse,
  type CreateSpaceRequest,
  type CreateSpaceResponse,
  type SpacesForUserResponse,
  type CollaborationSessionResponse,
  type DeleteSpaceItemResponse,
  type GetSpaceItemResponse,
  type GetSpaceItemsResponse,
  type CreateNotebookRequest,
  type CreateNotebookResponse,
  type GetNotebookResponse,
  type UpdateNotebookRequest,
  type UpdateNotebookResponse,
  type CreateLexicalRequest,
  type CreateLexicalResponse,
  type GetLexicalResponse,
  type UpdateLexicalRequest,
  type UpdateLexicalResponse,
  type CreditsResponse,
  type CreateDatasourceResponse,
  type GetDatasourceResponse,
  type ListDatasourcesResponse,
  type UpdateDatasourceResponse,
  type CreateSecretRequest,
  type CreateSecretResponse,
  type GetSecretResponse,
  type ListSecretsResponse,
  type UpdateSecretRequest,
  type UpdateSecretResponse,
  type SpaceJSON,
  type NotebookJSON,
  type LexicalJSON,
  type RuntimeSnapshotJSON,
  HealthCheck,
  type HealthCheckJSON,
  type LoginRequest,
  type LoginResponse,
  type UserMeResponse,
  type MembershipsResponse,
  type WhoAmIResponse,
  type HealthzPingResponse,
  AuthenticationManager,
  type IUser,
  type IBaseUser,
  type ICell,
  type IDatasource,
  type IDatasourceVariant,
  type ICredits,
  type ICreditsReservation,
  type ISpaceItem,
  type ISurvey,
  type ISpace,
  type IBaseSpace,
  type IAnySpace,
  type ISpaceVariant,
  type IBaseTeam,
  type IAnyTeam,
  type IOrganization,
  type IAnyOrganization,
  type IBaseOrganization,
  type IRuntimeModel,
  type IRuntimePod,
  type IRuntimeType,
  type IRuntimeLocation,
  type IRuntimeCapabilities,
  type IRuntimeSnapshot,
  type IDatalayerEnvironment,
  type IResources,
  type ISnippet,
  type IRole,
  type IAssignment,
  type IContact,
  type ICourse,
  type IOrganizationMember,
  type IPage,
  type PageTagName,
  type PageTheme,
  type PageVariant,
  type ISecret,
  type ISecretVariant,
  type SecretData,
  type SecretJSON,
  type DatasourceData,
  type DatasourceJSON,
  type DatasourceType,
  type CreateDatasourceRequest,
  type UpdateDatasourceRequest,
  Datasource,
  type IIAMToken,
  type IIAMTokenVariant,
  type IDocument,
  type IBaseDocument,
  type IEnvironment,
  type IExercise,
  type ICode,
  type IHelp,
  type IInvite,
  type ILesson,
  type INotebook,
  type IBaseNotebook,
  type ISchool,
  type ITeam,
  type TeamMember,
  type IUserOnboarding,
  type IClient,
  type IOnboardingPosition,
  type IOnboardingTours,
  type ITour,
  type ITourStatus,
  type IUserSettings,
  type IDataset,
  type IUsage,
  type IItem,
  type IItemType,
  type Member,
  type Profile,
  type SpaceMember,
  type IContactEvent,
  type IContactIAMProvider,
  type IStudentItem,
  type Instructor,
  type IStudent,
  type IDean,
  type IUserEvent,
  type IIAMProviderLinked,
  type IContent,
  type AuthResult,
  type TokenValidationResult,
  type AuthOptions,
  type TokenStorage,
  type IRuntimeOptions,
  type IMultiServiceManager,
  type IRemoteServicesManager,
  type IEnvironmentsManager,
  type IRemoteRuntimesManager,
  type IDatalayerCoreConfig,
  type IRuntimesConfiguration,
  type IIAMProviderName,
} from './client';
