# Copyright (c) 2023-2025 Datalayer, Inc.
# Distributed under the terms of the Modified BSD License.

SHELL=/bin/bash

.DEFAULT_GOAL := help

.PHONY: help quickstart quickstart-nocontext

help:
	@echo "Targets:"
	@echo "  quickstart            Run runtime_quickstart.py"
	@echo "  quickstart-nocontext  Run runtime_quickstart_nocontext.py"

quickstart:
	python runtime_quickstart.py

quickstart-nocontext:
	python runtime_quickstart_nocontext.py
