name: Check typing

on:
  push:
    branches:
      - main
    paths:
      - 'datalayer_core/**'
      - 'examples/decorator/**'
      - 'examples/fastapi-sklearn/**'
      - 'examples/pytorch-workloads/**'
      - 'examples/streamlit-sklearn/**'
      - 'pyproject.toml'
      - 'setup.py'
      - '.github/workflows/check-typing.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'datalayer_core/**'
      - 'examples/**/*.py'
      - 'examples/**/pyproject.toml'
      - 'examples/**/setup.py'
      - 'examples/**/requirements*.txt'
      - 'pyproject.toml'
      - 'setup.py'
      - '.github/workflows/check-typing.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-code-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: 3.12
          activate-environment: true

      - name: Install dependencies
        run: |
          uv pip install mypy
          uv pip install types-requests
      - name: Run mypy
        run: |
          mypy datalayer_core
