name: Check code style

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
    
jobs:
  check-code-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: 3.12
          activate-environment: true

      - name: Install dependencies
        run: |
          uv pip install .
          uv pip install pre-commit

      - name: Run pre-commit
        run: |
          pre-commit run --all-files    
