name: Run Basic Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    steps:

      - name: Install deps
        run: |
          sudo apt install libdbus-1-3 libdbus-1-dev libglib2.0-dev
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git to use https
        run: git config --global hub.protocol https

      - uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: ${{ matrix.python-version }}
          activate-environment: true

      - name: Install dev tools
        run: |
          uv pip install .
          uv pip install .[test]
          uv pip install secretstorage dbus-python keyring

      - uses: t1m0thyj/unlock-keyring@v1
      - name: Run basic tests
        env:
          DATALAYER_TEST_TOKEN: ${{ secrets.DATALAYER_TEST_TOKEN }}
        run: |
          pytest datalayer_core/tests/test_cli.py
          pytest datalayer_core/tests/test_sdk.py
